apiVersion: apps/v1
kind: Deployment
metadata:
  name: otp-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otp-backend
  template:
    metadata:
      labels:
        app: otp-backend
    spec:
      containers:
      - name: backend
        image: karthik26/otp-backend:v2
        ports:
        - containerPort: 4000
        env:
        - name: DB_HOST
          value: db
        - name: DB_USER
          value: postgres
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_PASSWORD
        - name: DB_NAME
          value: otpdb
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: JWT_SECRET
        - name: AWS_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: AWS_KEY
        - name: AWS_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: AWS_SECRET
        - name: AWS_REGION
          value: us-east-1
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: otp-backend
  ports:
  - port: 4000
    targetPort: 4000
