apiVersion: apps/v1
kind: Deployment
metadata:
  name: otp-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otp-frontend
  template:
    metadata:
      labels:
        app: otp-frontend
    spec:
      containers:
      - name: frontend
        image: karthik26/otp-frontend:ssl
        ports:
        - containerPort: 80
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort   # change to LoadBalancer for cloud
  selector:
    app: otp-frontend
  ports:
  - port: 80
    targetPort: 80
  - port: 443
    targetPort: 443
